import { Product } from "../model/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: crypto.randomUUID(),
    src: "/images/products/spinach.png",
    name: "Baby Spinach",
    unitInfo: "250 gm",
    price: "$2.19",
    category: "Vegetables",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/green-cabbage.png",
    name: "Green Cabbage",
    unitInfo: "200 gm",
    price: "$2.50",
    category: "Vegetables",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/red-apples.png",
    name: "Red Apples",
    unitInfo: "500 gm",
    price: "$2.50",
    category: "Fruits",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/banana.png",
    name: "Bananas",
    unitInfo: "1 Dozen",
    price: "$2.79",
    category: "Fruits",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/oranges.png",
    name: "Oranges",
    unitInfo: "1 kg",
    price: "$3.10",
    category: "Fruits",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/greek-yogurt.png",
    name: "Greek Yogurt",
    unitInfo: "200 gm",
    price: "$2.49",
    category: "Dairy",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/chocolate-milk.png",
    name: "Chocolate Milk",
    unitInfo: "100 ml",
    price: "$1.89",
    category: "Dairy",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/wheat-bread.png",
    name: "Wheat Bread",
    unitInfo: "1 loaf",
    price: "$2.99",
    category: "Bakery",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/beef-sirloin.png",
    name: "Beef Sirloin",
    unitInfo: "300 gm",
    price: "$6.49",
    category: "Meat",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/butter-block.png",
    name: "Butter Block",
    unitInfo: "250 gm",
    price: "$8.69",
    category: "Dairy",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/chocolate-muffin.png",
    name: "Chocolate Muffin",
    unitInfo: "4 pcs",
    price: "$3.19",
    category: "Bakery",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/croissant.png",
    name: "Croissant",
    unitInfo: "2 pcs",
    price: "$2.49",
    category: "Bakery",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/garlic-baguette.png",
    name: "Garlic Baguette",
    unitInfo: "1 pcs",
    price: "$3.29",
    category: "Bakery",
  },

  {
    id: crypto.randomUUID(),
    src: "/images/products/ground-beef.png",
    name: "Ground Beef",
    unitInfo: "500 gm",
    price: "$5.19",
    category: "Meat",
  },

  {
    id: crypto.randomUUID(),
    src: "/images/products/pineapple.png",
    name: "Pineapple",
    unitInfo: "1 pcs",
    price: "$2.35",
    category: "Fruits",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/smoked-sausage.png",
    name: "Smoked Sausage",
    unitInfo: "300 gm",
    price: "$3.99",
    category: "Meat",
  },
  {
    id: crypto.randomUUID(),
    src: "/images/products/sweet-corn.png",
    name: "Sweet Corn",
    unitInfo: "200 gm",
    price: "$2.49",
    category: "Vegetables",
  }
];