import { IProduct } from "../model/types";

export const MOCK_PRODUCTS: IProduct[] = [
  {
    id: 1,
    src: "/images/products/spinach.png", 
    name: "Baby Spinach",
    unitValue: 250,
    unit: "g",
    price: 2.19,
    category: "Vegetables",
    category_id: 1,
    quantity: 0,
  },
  {
    id: 2,
    src: "/images/products/green-cabbage.png", 
    name: "Green Cabbage",
    unitValue: 200,
    unit: "g",
    price: 2.5,
    category: "Vegetables",
    category_id: 1,
    quantity: 0,
  },
  {
    id: 3,
    src: "/images/products/red-apples.png", 
    name: "Red Apples",
    unitValue: 500,
    unit: "g",
    price: 2.5,
    category: "Fruits",
    category_id: 5,
    quantity: 0,
  },
  {
    id: 4,
    src: "/images/products/banana.png", 
    name: "Bananas",
    unitValue: 1,
    unit: "dozen",
    price: 2.79,
    category: "Fruits",
    category_id: 5,
    quantity: 0,
  },
  {
    id: 5,
    src: "/images/products/oranges.png", 
    name: "Oranges",
    unitValue: 1,
    unit: "kg",
    price: 3.1,
    category: "Fruits",
    category_id: 5,
    quantity: 0,
  },
  {
    id: 6,
    src: "/images/products/greek-yogurt.png", 
    name: "Greek Yogurt",
    unitValue: 200,
    unit: "g",
    price: 2.49,
    category: "Dairy",
    category_id: 4,
    quantity: 0,
  },
  {
    id: 7,
    src: "/images/products/chocolate-milk.png", 
    name: "Chocolate Milk",
    unitValue: 100,
    unit: "ml",
    price: 1.89,
    category: "Dairy",
    category_id: 4,
    quantity: 0,
  },
  {
    id: 8,
    src: "/images/products/wheat-bread.png", 
    name: "Wheat Bread",
    unitValue: 1,
    unit: "loaf",
    price: 2.99,
    category: "Bakery",
    category_id: 3,
    quantity: 0,
  },
  {
    id: 9,
    src: "/images/products/beef-sirloin.png", 
    name: "Beef Sirloin",
    unitValue: 300,
    unit: "g",
    price: 6.49,
    category: "Meat",
    category_id: 2,
    quantity: 0,
  },
  {
    id: 10,
    src: "/images/products/butter-block.png", 
    name: "Butter Block",
    unitValue: 250,
    unit: "g",
    price: 8.69,
    category: "Dairy",
    category_id: 4,
    quantity: 0,
  },
  {
    id: 11,
    src: "/images/products/chocolate-muffin.png", 
    name: "Chocolate Muffin",
    unitValue: 4,
    unit: "pcs",
    price: 3.19,
    category: "Bakery",
    category_id: 3,
    quantity: 0,
  },
  {
    id: 12,
    src: "/images/products/croissant.png", 
    name: "Croissant",
    unitValue: 2,
    unit: "pcs",
    price: 2.49,
    category: "Bakery",
    category_id: 3,
    quantity: 0,
  },
  {
    id: 13,
    src: "/images/products/garlic-baguette.png", 
    name: "Garlic Baguette",
    unitValue: 1,
    unit: "pcs",
    price: 3.29,
    category: "Bakery",
    category_id: 3,
    quantity: 0,
  },
  {
    id: 14,
    src: "/images/products/ground-beef.png", 
    name: "Ground Beef",
    unitValue: 500,
    unit: "g",
    price: 5.19,
    category: "Meat",
    category_id: 2,
    quantity: 0,
  },
  {
    id: 15,
    src: "/images/products/pineapple.png", 
    name: "Pineapple",
    unitValue: 1,
    unit: "pcs",
    price: 2.35,
    category: "Fruits",
    category_id: 5,
    quantity: 0,
  },
  {
    id: 16,
    src: "/images/products/smoked-sausage.png", 
    name: "Smoked Sausage",
    unitValue: 300,
    unit: "g",
    price: 3.99,
    category: "Meat",
    category_id: 2,
    quantity: 0,
  },
  {
    id: 17,
    src: "/images/products/sweet-corn.png", 
    name: "Sweet Corn",
    unitValue: 200,
    unit: "g",
    price: 2.49,
    category: "Vegetables",
    category_id: 1,
    quantity: 0,
  },
];
